### ISSUE TITLE
About ECB and CBC

### ISSUE THREAD

**Issue by anxiazifeng** [balena/aes-whitebox#2]
Hi，thank you for sharing this project.
I have a question about ECB and CBC.
As I know, OFB / CFB / CTR do Ciper with IV/nonce first, then XOR with original input, so encryption and decryption can be the same way.
But for ECB and CBC, the table in this project only support encryption I think, is that right ?

So if I want to make it support ECB and CBC, I should make decrypt_table or just make new Cipher method?

**Comment by anxiazifeng** [comment]
ECB and  CBC decryption need decrypt_table, issue solved ,thanks.

And hope this project support ECB and CBC later

**Comment by balena** [comment]
Hi @anxiazifeng, good you have solved your doubt.

Supporting ECB and CBC is out of the scope of this project because these need a completely new set of tables, and references are scarce, which makes this kind of work extremely complex.
