### ISSUE TITLE
Bug in the test file

### ISSUE THREAD

**Issue by NewDwarf** [balena/aes-whitebox#4]
https://github.com/balena/aes-whitebox/blob/master/aes_tests.c#L59
```
  read_hex(argv[2], plain, 4*16, "plain");
  read_hex(argv[3], iv_or_nonce, 16, "iv-or-nonce");
  read_hex(argv[4], cipher, 4*16, "cipher");
```
should be after the following if-else block.

**Comment by balena** [comment]
Hey @NewDwarf,

Actually it doesn't make any difference. The if/else is just initializing stuff, as well as read_hex. Actual work happens after these if-elses.

Regards,
Guilherme.
