### ISSUE TITLE
The file NTL/mat_GF2.h is missing

### ISSUE THREAD

**Issue by Twilight-Dream-Of-Magic** [balena/aes-whitebox#6]
https://github.com/balena/aes-whitebox/blob/master/aes_whitebox_compiler.cc#L11
https://github.com/balena/aes-whitebox/blob/master/aes_whitebox.cc#L7
https://github.com/balena/aes-whitebox/blob/master/aes_whitebox.cc#L41
https://github.com/balena/aes-whitebox/blob/master/aes_whitebox.cc#L105

Please fix

**Comment by moamen-gamal** [comment]
@Twilight-Dream-Of-Magic  you to need to add NTL library to your project [https://libntl.org/download.html](url) .

**Comment by balena** [comment]
👍
