### ISSUE TITLE
bugg : expression not evaluating to a constant 

### ISSUE THREAD

**Issue by hxm-cpp** [balena/aes-whitebox#8]
this line won't compile. 

https://github.com/balena/aes-whitebox/blob/master/aes_whitebox_compiler.cc#L162C1-L162C31

**Comment by balena** [comment]
Would you be more explicit? Would you list the exact error you're getting along with the compiler and version you have on your system?

**Comment by hxm-cpp** [comment]
```
>cl.exe /version
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x64
```
![image](https://github.com/balena/aes-whitebox/assets/116516702/d5f20800-2db3-4bf0-b2f8-e478b4dcf2b5)

**Comment by hxm-cpp** [comment]
i fixed it by hardcoding the values.

**Comment by balena** [comment]
I understand. Microsoft compilers have a long story of compatibility problems, and it sounds like another.

The generator code worked well on Clang and GCC compiler families, both on Linux and Mac.

My recommendation would be for you to compile the generator in Docker, under Linux/GCC, and execute it to produce the AES encoder from there. With the encoder source in hands, you can easily work with it on any C compiler.
